version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: task_manager_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: task_manager_user
      POSTGRES_PASSWORD: mysecretpassword
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: